### ISSUE TITLE
Layout bug report

### ISSUE THREAD

**Issue by eshill** [yiisoft-contrib/yiiframework.com#104] opened 2015-12-23 11:29 UTC
![yii_guide_bugs](https://cloud.githubusercontent.com/assets/11502920/11975600/8de11f60-a980-11e5-96a7-954263e590ea.png)
@jacmoe

**Comment by jacmoe** [comment] 2015-12-23 11:43
Where can I find those icons?
They are not in font-awesome or glyphicons?

**Comment by jacmoe** [comment] 2015-12-23 11:43
@samdark It is not a bug - it's Bootstrap :-1:  :)

**Comment by jacmoe** [comment] 2015-12-23 11:45
Thanks for the bug report - I was waiting for it :+1:

**Comment by samdark** [comment] 2015-12-23 11:47
@eshill can you export SVGs for guide icons and logo?

**Comment by jacmoe** [comment] 2015-12-23 11:48
We already have the logo in svg :)

**Comment by samdark** [comment] 2015-12-23 11:57
Guide icons only then.

**Comment by cebe** [comment] 2015-12-23 12:02
@eshill that look really cool, how did you make this report?

**Comment by jacmoe** [comment] 2015-12-23 12:52
I will **not** remove the caret from the guide navigation - how are you supposed to know that it is a accordion header?

**Comment by jacmoe** [comment] 2015-12-23 13:16
@eshill Grid width is? Base font-size is?
The grid width seems to be 1170 but there is no way that the guide group-list accordion based nav can fit in only two columns.
![yiiguide6](https://cloud.githubusercontent.com/assets/85424/11977099/b27b9608-a97f-11e5-9238-9b4081af7395.jpg)

**Comment by jacmoe** [comment] 2015-12-23 13:28
The chevron in the guide nav should be removed? It is an accordion, a list group, not a plain list.

**Comment by eshill** [comment] 2015-12-23 13:42
@cebe >how did you make this report?
Photoshop :-)

**Comment by eshill** [comment] 2015-12-23 13:48
@jacmoe 
> The chevron in the guide nav should be removed? It is an accordion, a list group, not a plain list.
Think yes, since all (!) the items have attachments subgroups - chevron is not needed.

**Comment by eshill** [comment] 2015-12-23 14:02
[guide_icons_svg.zip](https://github.com/yiisoft-contrib/yiiframework.com/files/70848/guide_icons_svg.zip)

**Comment by eshill** [comment] 2015-12-23 14:31
@jacmoe 
> The grid width seems to be 1170 but there is no way that the guide group-list accordion based nav can fit in only two columns.

Max grid width 1170. I don't understand what's the problem?

**Comment by jacmoe** [comment] 2015-12-23 15:57
> Max grid width 1170. I don't understand what's the problem?

I don't understand that either :p
I am good :+1:

**Comment by jacmoe** [comment] 2015-12-23 18:25
Updated blockquote icons in 5c7c80802f04eeb70c8ec78afaf9feebf5a8dc54

**Comment by samdark** [comment] 2015-12-23 19:27
:+1:

**Comment by jacmoe** [comment] 2016-01-02 12:20
@eshill could you check again please to see if I fixed the issues? :)

**Comment by cebe** [comment] 2016-01-02 13:50
there is one little issue with the language dropdown for "Português brasileiro". the dropdown is not wide enough for this language:

![bildschirmfoto von 2016-01-02 14 49 33](https://cloud.githubusercontent.com/assets/189796/12074659/3516dcac-b160-11e5-978a-c88a47393243.png)

**Comment by jacmoe** [comment] 2016-01-02 14:03
Would it fit if it was abbreviated to 'Portugues Brasil' ?

**Comment by cebe** [comment] 2016-01-02 14:07
still does not fit completely, also not sure if that is a valid abbreviation.

**Comment by samdark** [comment] 2016-01-02 14:08
It should adjust width based on content.

**Comment by jacmoe** [comment] 2016-01-02 15:59
It can't adjust width based on content.
The grid layout that Sergei uses has 4 columns for the nav buttons - but changing it to 5 columns solves the Portuguese Brasiliero problem.

**Comment by samdark** [comment] 2016-01-02 16:07
![qip shot - screen 392](https://cloud.githubusercontent.com/assets/47294/12075029/7ce57106-b183-11e5-9255-7dfa0de76a64.png)

First, remove `col-md-offset-8 col-md-4` from container. Then:

```css
.version-selector {
    float: right;

    .btn-group-justified {
        width: auto;
    }

    .btn-group-justified>.btn, .btn-group-justified>.btn-group {
        width: auto;
    }
}
```

**Comment by jacmoe** [comment] 2016-01-02 16:11
Yes, you can do that, but then the layout of the buttons will bounce every time the selected changes.
And I am not sure how it looks layout-wise.
Will keep that solution in mind, though.
IMO, it is better that the nav is aligned to the grid. :)

**Comment by cebe** [comment] 2016-01-02 16:17
what about aligning to the grid with min-width but allow it to become wider if content is too wide? So it would be aligned with the grid in nearly all cases.

**Comment by jacmoe** [comment] 2016-01-03 16:18
I know that it is very tempting to solve the problem properly for all possible circumstance - programmers tend to want that - but I consider the issue with the nav buttons to be solved because it works with *Portuguese Brasiliero* ;)

**Comment by cebe** [comment] 2016-01-03 17:17
okay, I was not aware of it being fixed already when I commented.

@eshill can we close this?

**Comment by samdark** [comment] 2016-01-03 17:47
Well, not all things are changed as suggested.

-

**Comment by eshill** [comment] 2016-01-03 18:52
![2016-01-03 21-52-09 8de11f60-a980-11e5-96a7-954263e590ea png 2500x2000](https://cloud.githubusercontent.com/assets/11502920/12080192/45d1d0ec-b264-11e5-9ba3-458079c65ebe.png)
font-size: 13px;

**Comment by eshill** [comment] 2016-01-03 18:53
![2016-01-03 21-52-52 8de11f60-a980-11e5-96a7-954263e590ea png 2500x2000](https://cloud.githubusercontent.com/assets/11502920/12080194/5c7b5afc-b264-11e5-9cfc-8c7a5ab5fc3a.png)

**Comment by eshill** [comment] 2016-01-03 18:54
![2016-01-03 21-53-48 2016-01-03 21-53-22 yii 2 0 - yii php framework png](https://cloud.githubusercontent.com/assets/11502920/12080197/83cd324c-b264-11e5-8ee1-ffce36cf083a.png)

**Comment by eshill** [comment] 2016-01-03 18:57
may be link  animation is faster?
transition: all ease-in-out .2s;

**Comment by eshill** [comment] 2016-01-03 19:00
for discussion:
can the accordion be like here - https://jqueryui.com/accordion/
when one item is opened - the other is automatically closed?

**Comment by jacmoe** [comment] 2016-01-03 19:29
I don't think that is a good idea because it makes it awkward to browse sections to see what's in them without leaving the page you are on.

**Comment by jacmoe** [comment] 2016-01-03 19:37
To make the menu highlight the current section for guide/API we need to override the default behaviour of the standard Yii2 bootstrap menu to make it active based on controller instead of route.
I don't know what the best way of doing that would be :)

**Comment by cebe** [comment] 2016-01-03 19:57
> override the hell out of the is item active function.

I can do that.



> I don't think that is a good idea because it makes it awkward to browse sections to see what's in them without leaving the page you are on.
> I like to look ahead when I read the guide.

same here, I think clicking on one section should leave the other untouched.

**Comment by cebe** [comment] 2016-01-03 20:05
> override the hell out of the is item active function.

done.

**Comment by jacmoe** [comment] 2016-01-03 20:08
That was elegant @cebe :+1:

**Comment by eshill** [comment] 2016-01-04 08:51
need to remove border here
![2016-01-04 11-49-55 yii 2 0 - yii php framework](https://cloud.githubusercontent.com/assets/11502920/12086253/4f9fdb12-b2d9-11e5-9b90-8ad965f5fc57.png)

and here

![2016-01-04 11-51-02 yii 2 0 - yii php framework](https://cloud.githubusercontent.com/assets/11502920/12086275/73e9c2c6-b2d9-11e5-9ce6-f1a32d297838.png)

**Comment by jacmoe** [comment] 2016-01-04 08:54
I am not sure what borders need to be removed?

**Comment by eshill** [comment] 2016-01-04 08:56
offer all opened submenu background-color: #f4fafb
![2016-01-04 11-54-31 yii 2 0 - yii php framework](https://cloud.githubusercontent.com/assets/11502920/12086340/37c1d292-b2da-11e5-956d-61cee6c9714d.png)

**Comment by eshill** [comment] 2016-01-04 09:01
I'm about this borders
![111](https://cloud.githubusercontent.com/assets/11502920/12086384/bfe2e422-b2da-11e5-9090-63dac8f29abe.jpg)

and this
![222](https://cloud.githubusercontent.com/assets/11502920/12086402/f072ce04-b2da-11e5-8d5d-e1f81f50c7fc.jpg)

**Comment by eshill** [comment] 2016-01-05 07:50
![untitled-1](https://cloud.githubusercontent.com/assets/11502920/12110145/20143246-b39a-11e5-8107-1778e17f300f.jpg)

**Comment by jacmoe** [comment] 2016-01-05 11:27
That has now been fixed - it was a copy'n'paste error that was introduced in one of the latest commits.

**Comment by jacmoe** [comment] 2016-01-05 11:28
I will remove the borders later - I didn't notice the border on the Guide index. Could be crappy monitor or my old eyes. :p

**Comment by jacmoe** [comment] 2016-01-06 19:50
Done all :)

I think that I will close this issue - open a new and fresh bug report if you have more input @eshill :)

**Closed by jacmoe** 2016-01-06 19:50 UTC
Labels: bug
