### ISSUE TITLE
Yii Framework Extention Image not load

### ISSUE THREAD

**Issue by vishuB** [yiisoft-contrib/yiiframework.com#265] opened 2018-03-23 12:52 UTC
In [yii2-opcache](https://www.yiiframework.com/extension/insolita/yii2-opcache) Extention image is not load.

![fireshot capture 006 - screenshot from 2018-03-23 18-17-17 p_ - file____home_rudra_desktop_screens](https://user-images.githubusercontent.com/13677102/37830003-272130ac-2ec7-11e8-9c0b-59ca91269381.png)

**Comment by samdark** [comment] 2018-03-23 15:20
@cebe is that about proxying images?

**Comment by cebe** [comment] 2018-03-23 15:48
duplicate of #261

**Closed by cebe** 2018-03-23 15:48 UTC
Labels: bug
