### ISSUE TITLE
Difficulties with horizoltal scroll

### ISSUE THREAD

**Issue by spinitron** [yiisoft-contrib/yiiframework.com#357] opened 2018-06-02 19:27 UTC
https://www.yiiframework.com/doc/api/2.0/yii-db-activequery#joinWith()-detail 

I cannot scroll leftwards in order to read the parameter descriptions. As a workaround I expand the browser window to about 1.5x my display panel's width.

Firefox 60.0.1 Mac

**Comment by rob006** [comment] 2018-06-02 20:08
Duplicate of #338

**Closed** 2018-06-03 07:20 UTC
