### ISSUE TITLE
Extensions - loading external images

### ISSUE THREAD

**Issue by lubosdz** [yiisoft-contrib/yiiframework.com#322] opened 2018-04-02 21:40 UTC
Due to referrer's `strict-policy` extern images are not loaded from external URLs.
Example [here ](https://www.yiiframework.com/extension/zhuravljov/yii2-rest) or [here - demo screenshots](https://www.yiiframework.com/extension/captcha-extended).

This used to work fine on previous site.

Should new site not allow loading external images then it would be good to explain how to insert them. Uploading images currently does not work. I tried to load PNG image 8 kB which turned after upload into 6 and 9 MB PNG image (perhaps wrong settings for resizing?). Then I tried to delete these 6 & 9 MB images but got error "An internal server error occured". I am logged in via gmail account which was connected/assigned to my previous site account - perhaps this may help .. ? (deleting image checks for previous user ID, though should also check for connected account).

**Comment by samdark** [comment] 2018-04-02 22:45
Duplicate of https://github.com/yiisoft-contrib/yiiframework.com/issues/261

**Closed by samdark** 2018-04-02 22:45 UTC
