### ISSUE TITLE
Header API Link works strange

### ISSUE THREAD

**Issue by e-h-h** [yiisoft-contrib/yiiframework.com#403] opened 2018-10-01 06:37 UTC
Link on API menu item(https://www.yiiframework.com/doc/api) gives me an JSON. The only browser affected is Chrome. 

Given JSON: https://drive.google.com/file/d/17b01RyPFf2jVHcWdYMofFLWBHImHAvTR

Video with bug: https://drive.google.com/open?id=1QNk8nXXxMNCF7hMAjE1v5uHpWOuClm1R

Browser info:
Chromium | 69.0.3497.81 (Официальная сборка) Built on Ubuntu , running on Ubuntu 16.04 (64 бит)
-- | --
Версия | 032b3ca19e9af20182f9bd03deefc0faf4695558-refs/branch-heads/3497@{#869}
ОС | Linux
JavaScript | V8 6.9.427.19
Flash | (отключено)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36
Командная строка | /usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --flag-switches-end
Путь к исполняемому файлу | /usr/lib/chromium-browser/chromium-browser
Путь к профилю | /home/teo/.config/chromium/Default

**Comment by samdark** [comment] 2018-10-01 18:47
@cebe does that look like API search index?

**Comment by e-h-h** [comment] 2018-10-02 06:31
No problem now. Same PC, same browser, even same instance of browser.

**Comment by samdark** [comment] 2018-10-02 10:16
OK. Closing it for now then...

**Closed by samdark** 2018-10-02 10:16 UTC
Labels: bug

**Comment by rob006** [comment] 2018-10-02 14:20
I was able to reproduce it. It looks like issue with browser caching - `Ctrl`+`F5` "fixed" this.

Steps to reproduce:

1. Open in private/incognito mode https://www.yiiframework.com/
2. Try to search something. 
3. Go to https://www.yiiframework.com/doc/api

`https://www.yiiframework.com/doc/api` result is cached in browser during searching. When you try to open it again, browser cache is used, but contains JSON (this is format expected by search) instead of HTML version.

**Comment by cebe** [comment] 2018-10-03 14:10
that's weird, I thought browser cache would vary by content type...

**Comment by cebe** [comment] 2018-10-03 14:35
should be fixed now. Thanks for reporting!
